# -*- coding: utf-8 -*-
"""hw2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164OI2GamqI99N9mNhU4UThybua0L0qjX
"""

#개념 확인 과제 4.7

total=int(input("총 금액 : "))

def exchange(m):
  m500=m//500
  m%=500
  m100=m//100
  m%=100
  m50=m//50
  m%=50
  m10=m//10

  print("500원 동전의 개수: ",m500)
  print("100원 동전의 개수: ",m100)
  print("50원 동전의 개수: ",m50)
  print("10원 동전의 개수: ",m10)

exchange(total)