# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hE54v4LOcBKqRF5Q5ElyvABOOhiGgjvG
"""

#할인
#202410993박현준

def get_fixed_price(percent, price):
  p=price*100//(100-percent)
  return p

percent=int(input("할인율은? "))
a=int(input("A 상품의 할인된 가격은? "))
b=int(input("B 상품의 할인된 가격은? "))

print(f"A 상품의 정가는 {get_fixed_price(percent, a)} 원")
print(f"B 상품의 정가는 {get_fixed_price(percent, b)} 원")