# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jU4HYQxl-Vzspdbq7LLktI22Zislx9rR
"""

#환영 메시지
#202410993 박현준

def hello(name):
  msg1 = f"Hello {name},"
  msg2 = "Wellcom to Seoul."
  a = len(msg1) if len(msg1) > len(msg2) else len(msg2)
  print("-"*(a+2))
  print(f" {msg1} ")
  print(f" {msg2} ")
  print("-"*(a+2))

hello(input("Input his/her name : "))