# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3sVzk9fNaHcyT9NSeEmrfN-WxvAV_R7
"""

#구구단

def rnrneks():
  n = 2
  for a in range(2) :
    for i in range(1,10) :
      for j in range(n,n+4) :
        print(f"{j} x {i} = {j*i:2d}", end = "     ")
      print()
    n = 6
    print()

rnrneks()