# -*- coding: utf-8 -*-
"""hw7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CpzWL1IRy-X_uhEDrtzU8eT3tM1S5Zt
"""

#202410993 박현준
#9주차 개념 확인 과제

shopping_bag = {}
print("[구입]")
while 1:
  item = input("상품명? ")
  if item == "":
    print()
    break
  else :
    num = int(input("수랑은? "))
    print(f"장바구니에 {item} {num}개가 담겼습니다.")
    shopping_bag[item] = num
    print()

print(f">>>장바구니 보기: {shopping_bag}")
print()

print("[검색]")
search = input("장바구니에서 확인하고자 하는 상품은? ")
print(f"{search}은(는) {shopping_bag.get(search)}개 담겨있습니다.")